POST http://127.0.0.1:8000/api/change-password/ HTTP/1.1
Content-Type: application/json
Authorization: Token 299d506ec3da314fe7fd1095666ed50c755a645a

{
    "old_password": "testpassword",
    "new_password": "password",
    "confrim_password": "password"
}

###
POST http://127.0.0.1:8000/api/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Token 23ad3ac4319018fdfdf46187de98b2c0a2c0857b

###
POST http://127.0.0.1:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "testusers1",
    "email": "testuser@test.test",
    "password": "testpassword",
    "password2": "testpassword"
}

###

POST http://127.0.0.1:8000/api/confirm-email/12/cjjf5b-1837ab30f0be266b92ce08c4acf04729/ HTTP/1.1


###
GET http://127.0.0.1:8000/api/user/ HTTP/1.1
Authorization: Token 0b2a538bc51978fb9b5f4d604fb2ac2fbf8ae255

###
GET http://127.0.0.1:8000/api/user/ HTTP/1.1
Content-Type: application/json
Authorization: Token 178bd499cf3b5944184815b0bdef646794ecc900

{
    "username": "updated_username",
    "email": "testapp@test.test",
    "first_name": "Instance_name",
    "last_name": "updated_name"
}

###
GET http://127.0.0.1:8000/api/users/ HTTP/1.1

Content-Type: application/json