POST http://127.0.0.1:8000/api/change-password/ HTTP/1.1
Content-Type: application/json
Authorization: Token 299d506ec3da314fe7fd1095666ed50c755a645a

{
    "old_password": "testpassword",
    "new_password": "password",
    "confrim_password": "password"
}

###
POST http://127.0.0.1:8000/api/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Token 299d506ec3da314fe7fd1095666ed50c755a645a

###
POST http://127.0.0.1:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "testuser1",
    "email": "testuser@test.test",
    "password": "testpassword1",
    "password2": "testpassword1"
}

###

POST http://127.0.0.1:8000/api/confirm-email/7/cjb3om-dd49e1f17b98dea01c5fffa994d9914b/ HTTP/1.1


###
GET http://127.0.0.1:8000/api/user/ HTTP/1.1
Authorization: Token 299d506ec3da314fe7fd1095666ed50c755a645a