# Generated by Django 5.1.4 on 2025-12-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_account", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="socialprovider",
            constraint=models.UniqueConstraint(
                fields=("provider", "client_id", "secret_key"),
                name="social_provider_unique",
            ),
        ),
    ]
