# Generated by Django 5.1.4 on 2025-12-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_account", "0002_socialprovider_social_provider_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="profile_url",
            field=models.URLField(default=""),
        ),
    ]
