# Generated by Django 5.1.4 on 2025-12-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_account", "0003_socialaccount_profile_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="access_token",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="refresh_token",
            field=models.CharField(default="", max_length=200),
        ),
    ]
