# Generated by Django 5.1.4 on 2025-12-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_account", "0004_socialaccount_access_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, default="", max_length=100)),
                (
                    "state",
                    models.CharField(default="9h3PalauFdinonLkQstrEA", max_length=100),
                ),
                ("expired", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
