# Generated by Django 5.1.4 on 2025-12-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_auth", "0002_emailconfirmation_is_expired_emailconfirmation_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailconfirmation",
            old_name="timestamp",
            new_name="sent_at",
        ),
        migrations.RemoveField(
            model_name="emailconfirmation",
            name="is_expired",
        ),
        migrations.AlterField(
            model_name="emailconfirmation",
            name="token",
            field=models.CharField(default="", max_length=100),
        ),
    ]
